title: Default Page

permissions:
  extends: options/permissions

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: medium
  sidebar:
    width: 1/3
    sections:
      files:
        type: files

