title: Page

permissions:
  extends: options/permissions

tabs:

  article:
    label: ✍️ Article 📑
    fields:
      builder: fields/blocks

  skin:
    label: 💅 Fashun 💄
    fields:
      skin: fields/skins
