type: pages
headline: Site
templates:
  - home
  - error
empty: No page yet
layout: table
image: false 
info: false
columns:
  modified:
    label: Last Modified
    value: '{{ page.modified('d/m/Y H:i') }}'
